name: "Resol VBus"
description: "Addon to provide json VBus data and emulate Extension Modules for Resol Deltasol controllers."
version: "0.0.1"
slug: "resol_vbus"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  host: ""
  password: "vbus"
  sensors: []
  json_server: false
schema:
  host: str
  password: str
  sensors:
    - str
  json_server: bool
